fix: recorrencias desconfigurado
lfreneda/recurring pull request #4
Opened 2024-10-18 15:38 UTC by guilherme-carmona

ajustada a lógica da biblioteca para que ela ignore os finais de semana apenas quando o intervalo é diário, em vez de mover para o próximo dia útil, isso porque alguns clientes estavam reclamando que, ao gerar um intervalo de 2 dias, acabava ficando com dias como 'segunda, terça e quinta' devido ao deslocamento do domingo para a segunda

2024-10-18 15:40 UTC, Carlos-F-Braga approved these changes

2024-10-18 16:34 UTC, rafaelcaniello approved these changes

2024-11-05 20:08 UTC, cesarfield approved these changes

2024-11-18 14:29 UTC, caiorsantanna requested changes
Não faz sentido, se ele pediu para ignorar os fins de semana, é o que a lib ta fazendo, ignorando o fim de semana kkkk, pedir pro cliente alterar para escolher o fim de semana não resolve o caso dele?

2024-11-18 16:47 UTC, rafaelcaniello commented
> Não faz sentido, se ele pediu para ignorar os fins de semana, é o que a lib ta fazendo, ignorando o fim de semana kkkk, pedir pro cliente alterar para escolher o fim de semana não resolve o caso dele?

o problema que esse PR resolve é a contagem de dias em diferentes intervalos ignorando o fim de semana. 
Por exemplo, quando colocado 2 dias de intervalo ele gera as atividades assim:
Semana ímpar: Segunda, Quarta e Sexta
Semana par: Segunda, Terça e Quinta

quando a contagem parava no fim de semana ele colocava para Segunda causando esse erro na contagem.

2025-06-06 18:41 UTC, closed without merging